version: "3"
   
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: muestra_docker_web
    volumes:
      - .:/code
    ports:
      - "8000:8000"

